# Automatically updated by the winget bot
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Audio_Arcade.Audio_Arcade
PackageVersion: "3.0.0"
InstallerType: exe
Installers:
  - InstallerUrl: https://github.com/Audio-Arcade/Audio_Arcade/releases/download/Release/Audio_Arcade.exe
    Architecture: x64
    InstallerSha256: 8b74c6c25d1f8ab9ea57a90345d2666fdb76a99b9644e3c4288a879b4e61fd26
  - InstallerUrl: https://github.com/Audio-Arcade/Audio_Arcade/releases/download/Release/Audio_Arcade.msi
    Architecture: x64
    InstallerSha256: 735277b92493bbb16a429540dc7427bc855a62a081ad2b9b6575d0a34b785c43
ManifestType: installer
ManifestVersion: 1.10.0
